### ISSUE TITLE
我现在是在提问题吗

### ISSUE THREAD

**Issue by choubaguai** [kongnanlive/SideBar#4]
请问下，能否做成通讯录那种，

**Comment by kongnanlive** [comment]
你代码拿去改好了

**Comment by choubaguai** [comment]
改了，但是水平有限，每次滑动的时候列表并不能实时变化，只有在手指离开屏幕的时候，列表才会到达指定位置，希望能得到你的帮助

**Comment by kongnanlive** [comment]
` mChoose = characterIndex;
                            Log.d(TAG, "mChoose " + mChoose + " mLetterHeight " + mLetterHeight);
//                            mOnTouchingLetterChangedListener.onTouchingLetterChanged(mLetters[characterIndex]);`

这里

**Comment by kongnanlive** [comment]
@superbro0 
`mChoose = characterIndex; Log.d(TAG, "mChoose " + mChoose + " mLetterHeight " + mLetterHeight); 
// mOnTouchingLetterChangedListener.onTouchingLetterChanged(mLetters[characterIndex]);
`
这里注释放开
`if (mIsBeingDragged) {
                       //  mOnTouchingLetterChangedListener.onTouchingLetterChanged(mLetters[mChoose]);
                    }`
这里加上注释避免重发触发

**Comment by choubaguai** [comment]
@kongnanlive 好的，我试试，谢谢啊。

**Comment by choubaguai** [comment]
@kongnanlive 好啦，成功了，哈哈，谢谢
